# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plotControlWrapper(object):
    def setupUi(self, plotControlWrapper):
        plotControlWrapper.setObjectName("plotControlWrapper")
        plotControlWrapper.resize(535, 212)
        self.horizontalLayout = QtWidgets.QHBoxLayout(plotControlWrapper)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_plot_wrap = QtWidgets.QWidget(plotControlWrapper)
        self.horizontalLayout_plot_wrap.setObjectName("horizontalLayout_plot_wrap")
        self.horizontalLayout_plot = QtWidgets.QHBoxLayout(self.horizontalLayout_plot_wrap)
        self.horizontalLayout_plot.setObjectName("horizontalLayout_plot")
        self.checkBox_plot = QtWidgets.QCheckBox(self.horizontalLayout_plot_wrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_plot.sizePolicy().hasHeightForWidth())
        self.checkBox_plot.setSizePolicy(sizePolicy)
        self.checkBox_plot.setText("")
        self.checkBox_plot.setObjectName("checkBox_plot")
        self.horizontalLayout_plot.addWidget(self.checkBox_plot)
        self.label_plot = QtWidgets.QLabel(self.horizontalLayout_plot_wrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_plot.sizePolicy().hasHeightForWidth())
        self.label_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_plot.setFont(font)
        self.label_plot.setObjectName("label_plot")
        self.horizontalLayout_plot.addWidget(self.label_plot)
        self.toolButton_plotCol = QtWidgets.QToolButton(self.horizontalLayout_plot_wrap)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/Images/assets/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_plotCol.setIcon(icon)
        self.toolButton_plotCol.setObjectName("toolButton_plotCol")
        self.horizontalLayout_plot.addWidget(self.toolButton_plotCol)
        self.button_SOS = QtWidgets.QPushButton(self.horizontalLayout_plot_wrap)
        self.button_SOS.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_SOS.sizePolicy().hasHeightForWidth())
        self.button_SOS.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/Images/assets/add_SOS.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.button_SOS.setIcon(icon2)
        #self.button_SOS.setMaximumSize(QtCore.QSize(23, 22))
        #self.button_SOS.setFocusPolicy(QtCore.Qt.TabFocus)
        self.button_SOS.setObjectName("button_SOS")
        self.horizontalLayout_plot.addWidget(self.button_SOS)
        self.toolButton_plotDel = QtWidgets.QToolButton(self.horizontalLayout_plot_wrap)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/Images/assets/trashCan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_plotDel.setIcon(icon1)
        self.toolButton_plotDel.setObjectName("toolButton_plotDel")
        self.horizontalLayout_plot.addWidget(self.toolButton_plotDel)
        self.horizontalLayout.addWidget(self.horizontalLayout_plot_wrap)

        self.retranslateUi(plotControlWrapper)
        QtCore.QMetaObject.connectSlotsByName(plotControlWrapper)

    def retranslateUi(self, plotControlWrapper):
        _translate = QtCore.QCoreApplication.translate
        plotControlWrapper.setWindowTitle(_translate("plotControlWrapper", "Form"))
        self.label_plot.setText(_translate("plotControlWrapper", "plotName"))
        self.toolButton_plotCol.setText(_translate("plotControlWrapper", "..."))
        self.button_SOS.setText(_translate("plotControlWrapper", "..."))
        self.toolButton_plotDel.setText(_translate("plotControlWrapper", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    plotControlWrapper = QtWidgets.QWidget()
    ui = Ui_plotControlWrapper()
    ui.setupUi(plotControlWrapper)
    plotControlWrapper.show()
    sys.exit(app.exec_())
