# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stages.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 743)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_zone = QtWidgets.QVBoxLayout()
        self.show_zone.setContentsMargins(1, -1, -1, -1)
        self.show_zone.setObjectName("show_zone")
        self.chk_all_selected = QtWidgets.QRadioButton(MainWindow)
        self.chk_all_selected.setObjectName("chk_all_selected")
        self.show_zone.addWidget(self.chk_all_selected)
        self.horizontalLayout.addLayout(self.show_zone)
        self.GraphZone = QtWidgets.QVBoxLayout()
        self.GraphZone.setSpacing(6)
        self.GraphZone.setObjectName("GraphZone")
        self.GraphsWidget = QtWidgets.QTabWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphsWidget.sizePolicy().hasHeightForWidth())
        self.GraphsWidget.setSizePolicy(sizePolicy)
        self.GraphsWidget.setMinimumSize(QtCore.QSize(780, 390))
        self.GraphsWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.GraphsWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.GraphsWidget.setTabBarAutoHide(False)
        self.GraphsWidget.setObjectName("GraphsWidget")
        self.MagTab = QtWidgets.QWidget()
        self.MagTab.setObjectName("MagTab")
        self.GraphsWidget.addTab(self.MagTab, "")
        self.AtenTab = QtWidgets.QWidget()
        self.AtenTab.setObjectName("AtenTab")
        self.GraphsWidget.addTab(self.AtenTab, "")
        self.FaseTab = QtWidgets.QWidget()
        self.FaseTab.setObjectName("FaseTab")
        self.GraphsWidget.addTab(self.FaseTab, "")
        self.RetGrupTab = QtWidgets.QWidget()
        self.RetGrupTab.setObjectName("RetGrupTab")
        self.GraphsWidget.addTab(self.RetGrupTab, "")
        self.PazTab = QtWidgets.QWidget()
        self.PazTab.setObjectName("PazTab")
        self.GraphsWidget.addTab(self.PazTab, "")
        self.RespImpTab = QtWidgets.QWidget()
        self.RespImpTab.setObjectName("RespImpTab")
        self.GraphsWidget.addTab(self.RespImpTab, "")
        self.RespEscTab = QtWidgets.QWidget()
        self.RespEscTab.setObjectName("RespEscTab")
        self.GraphsWidget.addTab(self.RespEscTab, "")
        self.GraphZone.addWidget(self.GraphsWidget)
        self.groupBox = QtWidgets.QGroupBox(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 1221212))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FilterList = QtWidgets.QListWidget(self.groupBox)
        self.FilterList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterList.sizePolicy().hasHeightForWidth())
        self.FilterList.setSizePolicy(sizePolicy)
        self.FilterList.setResizeMode(QtWidgets.QListView.Adjust)
        self.FilterList.setObjectName("FilterList")
        self.verticalLayout.addWidget(self.FilterList)
        self.GraphZone.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.GraphZone)

        self.retranslateUi(MainWindow)
        self.GraphsWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filter Tool G4"))
        self.chk_all_selected.setText(_translate("MainWindow", "Acumulada "))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.MagTab), _translate("MainWindow", "Magnitud"))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.AtenTab), _translate("MainWindow", "Atenuación"))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.FaseTab), _translate("MainWindow", "Fase"))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.RetGrupTab), _translate("MainWindow", "Ret. Grupo"))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.PazTab), _translate("MainWindow", "P and Z"))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.RespImpTab), _translate("MainWindow", "Resp. Imp."))
        self.GraphsWidget.setTabText(self.GraphsWidget.indexOf(self.RespEscTab), _translate("MainWindow", "Resp. Esc."))
        self.groupBox.setTitle(_translate("MainWindow", "Lista de Filtros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
